### ISSUE TITLE
Read, parse and publish to PubSub GCN Circulars

### ISSUE THREAD

**Issue by mjuric** [scimma/client_library#4]
As a user, I want to be able to inject [GCN Circulars](https://gcn.gsfc.nasa.gov/gcn3_archive.html) (which appear to be [RFC 822](https://tools.ietf.org/html/rfc822) formatted?) into the PubSub system. The GCN circular should be parsed and posted in a JSON wrapper with the following schema:
```
{
"headers": {
    "title": "xxxx",
     .....
},
body: "xxxx" 
}
```
Definition of done:
- `scimma publish -f 26919.gcn3` must read the message in file 26919.gcn3, serialize it as JSON, and publish it to the 'gcn' topic on the PubSub system.
- The `scimma publish` subcommand must show a useful help message if called w/o arguments
- Tests and documentation will exist for all new functionality

Tasks:
- [x] Create the `scimma` entry point
- [x] Develop necessary library functionality (parser, serializer, posting to Kafka)
- [x] Expose a friendly argparse cmdline interface
- [x] Write unit tests
- [x] Document the new functionality

**Comment by mjuric** [comment]
@myNameIsPatrick Can you add an example of a GCN to the repository -- maybe drop one into `tests/data`? It's useful to have one ready when following the examples in the `README.md`.

**Comment by myNameIsPatrick** [comment]
That's a great idea, I have embedded one for the tests but I can add the example I've been using. Do you prefer packaging the file or providing a method to grab one from the GCN archive, e.g. `wget https://gcn.gsfc.nasa.gov/gcn3/27030.gcn3`?

**Comment by mjuric** [comment]
They're small enough to just package one -- makes the repo self-contained (great for testing during long plane flights :) ).

**Comment by myNameIsPatrick** [comment]
Okay, one has been added into `tests/data` and its use is documented in the README.
