### ISSUE TITLE
Initial Sphinx documentation

### ISSUE THREAD

**Issue by mjuric** [scimma/client_library#6]
As a user, I want to be able to browse a series of HTML pages to learn about client functionality. Documentation source must be stored and versioned with the code (in the same git repository).

Definition of done:
- Show documentation built from Sphinx files, documenting all currently available client functionality.

Tasks
- [x] set up standard Sphinx scaffolding
- [x] document existing tasks
- [x] document the process how to build documentation in the README
- [x] consider [integrating with setup.py](https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html)

**Comment by myNameIsPatrick** [comment]
To clarify on the last checkbox, we get this for free via setuptools, so running `python setup.py build_sphinx` works without any modification.

**Comment by mjuric** [comment]
What do I need to have installed for the above command to work? Right now I'm getting:
```
$ python setup.py build_sphinx
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'build_sphinx'
```

**Comment by myNameIsPatrick** [comment]
I realize now that the section in the README is fairly sparse. You should be able to get the docs to build by installing one of the extras package, via `pip install scimma-client[docs]`.

**Comment by mjuric** [comment]
Got it, thanks.

Is the recommended way to build the docs while developing (i.e., when I don't want to install the package into `site-packages`, but keep changes local) to run make in `doc/`?

**Comment by myNameIsPatrick** [comment]
That's how I've always done it, unsure if that's what most people do though. Running `make doc` in the project root basically just runs the Makefile that sphinx provides when the scaffolding was set up, via `cd doc && make html`.

**Comment by mjuric** [comment]
👍 (I do the same, I was just curious if there was any setuptools magic I should be using instead that I didn't know about!).
