### ISSUE TITLE
Automate RTD documentation publication with GitHub actions

### ISSUE THREAD

**Issue by mjuric** [scimma/client_library#9]
As a user, I want a new version of the documentation to be automatically generated and uploaded to RTD for `master` and any released (tagged) versions.

Definition of done:
- Pushing (or merging) a new commit to `master` must trigger documentation rebuild and upload to RTD. Following the rebuild/upload, browsing the `master` documentation on RTD should reflect the documentation present on the most-recent master.
- Tagging a commit with a 'vX.X.X'-like tag should trigger actions to upload the corresponding documentation on RTD under the same version tag.
- Explore the ability to build/push to RTD docs for every PR. This would make it easy for a code reviewer to read documentation being PR-ed (if any).

Tasks
- [x] RTD docs get produced for every commit to `master`
- [x] Releases should correspond with new RTD doc versions

**Comment by myNameIsPatrick** [comment]
Waiting for #5 so that we can release a new proper version with the necessary RTD config so we can test out the release part of the RTD docs.
